server:
  port: 2002
  servlet:
    context-path: /generator
spring:
  application:
    name: springboot2-demo-generator
  cache:
    type: caffeine
    cache-names:
#      数据源放入缓存后保存30分钟
      dataSources: 1800
  profiles:
    active: dev